mongodata:
  image: mongo:3.0.14
  volumes:
    - /data/db
  command: --break-mongo

mongo:
  image: mongo:3.0.14
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles --rest
